# Generated by Django 3.2.9 on 2021-12-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['shippable_date'], 'permissions': (('can_adopt_book', 'adopt_book'),)},
        ),
    ]
