# Generated by Django 3.2.9 on 2021-12-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['shippable_date'], 'permissions': (('can_mark_book_adopted', 'set_book_as_adopted'),)},
        ),
    ]
